---
# takes variable network_name
- hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Include Wifi vars
      ansible.builtin.include_vars:
        file: ../vars/cac/wifi.yml
    
    - name: Include Wifi psks vault vars
      ansible.builtin.include_vars:
        file: ../vars/cac/wifi_psks_vault.yml    

    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
    
    - name: Debug Network Info
      ansible.builtin.debug:
        var: result
        verbosity: 2
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('name', 'equalto', network_name ) | list }}"
      register: network_id_get

    - debug: 
        var: network_id_get
     
    - name: Edit SSID Settings
      cisco.meraki.networks_wireless_ssids: 
        meraki_api_key: "{{ meraki_key }}"
        networkId: "{{ filtered_networks.0.id }}"
        enabled: "{{ item.enabled }}"
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        number: "{{ item.number }}"
        encryptionMode: "{{ item.authentication.encryption_mode }}"
        authMode: "{{ item.authentication.auth_mode }}"
        psk: "{{ SSID_PSKS[item.name] | default(SSID_PSKS['default_psk']) }}"
        wpaEncryptionMode: "{{ item.authentication.wpa_encryption_mode }}"
        visible: "{{ item.visible | default('true')  }}"
        availableOnAllAps: "{{ item.availableOnAllAps | default('false')  }}"
        useVlanTagging: "{{ item.vlan.useVlanTagging | default('false')  }}"
        defaultVlanId: "{{ item.vlan.defaultVlanId }}"
      delegate_to: localhost
      loop: "{{ SSID }}"
      no_log: true
